### ISSUE TITLE
Failed to run real-world example

### ISSUE THREAD

**Issue by jacklol13** [yelouafi/redux-saga#607]
The following happens after npm install & start:

```
$:/projects/redux-saga/examples/real-world$ npm start

> redux-real-world-example@1.0.0 start /projects/redux-saga/examples/real-world
> node --require babel-register server.js

/projects/redux-saga/examples/real-world/node_modules/redux-logger/lib/defaults.js:8
  logger: undefined && undefined.console || window && window.console,
                                            ^

ReferenceError: window is not defined
    at Object.<anonymous> (/projects/redux-saga/examples/real-world/node_modules/redux-logger/lib/defaults.js:8:45)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (/projects/redux-saga/examples/real-world/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/projects/redux-saga/examples/real-world/node_modules/redux-logger/lib/index.js:13:17)

npm ERR! Linux 3.13.0-92-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! redux-real-world-example@1.0.0 start: `node --require babel-register server.js`
npm ERR! Exit status 1
npm ERR! 
```

**Comment by Andarist** [comment]
Ive tried running the example and didnt encounter such problem, I've checked `/projects/redux-saga/examples/real-world/node_modules/redux-logger/lib/defaults.js` and has just `logger: console,` instead of `logger: undefined && undefined.console || window && window.console,` which appeared in the log you have pasted in.

Could you try reinstalling `node_modules`?

**Comment by jacklol13** [comment]
The previous command there was npm install, but strangely deleting node_modules and reinstalling solved this.
